import { NgModule } from '@angular/core';

import {
  MatButtonModule,
  MatCardModule,
  MatDialogModule,
  MatGridListModule,
  MatIconModule,
  MatInputModule,
  MatListModule,
  MatMenuModule,
  MatRippleModule,
  MatSnackBarModule,
  MatToolbarModule,
  MatLineModule,
  MatButtonToggleModule,
  MatFormFieldModule,
  MatSidenavModule,
  MatSelectModule,
  MatTabsModule,
  MatCheckboxModule,
  MatAutocompleteModule,
  MatDatepickerModule,
  MatRadioModule,
  MatSliderModule,
  MatSlideToggleModule,
  MatProgressBarModule,
  MatExpansionModule
} from '@angular/material';

@NgModule({
  imports: [
    MatButtonModule,
    MatCardModule,
    MatDialogModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatRippleModule,
    MatSnackBarModule,
    MatToolbarModule,
    MatLineModule,
    MatButtonToggleModule,
    MatFormFieldModule,
    MatSidenavModule,
    MatSelectModule,
    MatTabsModule,
    MatCheckboxModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    MatRadioModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatProgressBarModule,
    MatExpansionModule
  ],
  exports: [
    MatButtonModule,
    MatCardModule,
    MatDialogModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatRippleModule,
    MatSnackBarModule,
    MatToolbarModule,
    MatLineModule,
    MatButtonToggleModule,
    MatFormFieldModule,
    MatSidenavModule,
    MatSelectModule,
    MatTabsModule,
    MatCheckboxModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    MatRadioModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatProgressBarModule,
    MatExpansionModule
  ],
  declarations: []
})
export class AppMaterialModule { }
